### PR TITLE
Yoke and muon chambers fix

### PR DESCRIPTION
**Pull request by oviazlo**
- Change thickness of the Iron layer in the barrel and endcaps yoke to match FCCee specifications

### CODE REVIEW

**Comment by oviazlo** [comment]
Hi Yorgos,

I finished working on yoke and muon chambers. There are no overlaps, so it should be OK.
I discussed new numbers with Konrad and he said they look OK.

Sasha

**Comment by Voutsi** [comment]
Hi Sasha,

thanks a lot. I also finished with the remaining overlaps. So, in principle we are ready for testing. One possible addition would be to decrease the size of LumiCal to 30 layers (and maybe put it a bit further along Z), I will write to Mogens about that.

**Comment by oviazlo** [comment]
Hi Yorgos,

About cellID problem which I mentioned before. Looks like the issue is in
Vertex_o4_v02.xml file. If I use file from CLIC model for vertex detector
reconstruction works fine. Do you have any ideas why cellID's can be
differently assigned for FCCee? Thanks!

Cheers,
  Sasha

**Comment by Voutsi** [comment]
I am looking into it. We are using the same driver and readout as CLIC. One thing that we have to change is to reduce the number of modules in  endcaps from 8 to 6, but it doesn't seem to solve the problem...

**Comment by Voutsi** [comment]
Well, I found what caused it. It was how I was creating the assembly of envelope volumes for the VXD. However I admit that I still don't understand why it was creating the trouble... I will commit the fix later today.
Also my comment about the modules is not accurate, the layers are 6 but the modules are correctly 8.

Cheers,
Yorgos

**Comment by Voutsi** [comment]
Hi again Sasha,

despites sim & reco are running and the collections are populated, I am still getting crazy layer numbers (>100). I am using the software version from 28/03/17. However could be that I need to update my analysis processor, I am checking it.

**Pull request merged**
